NAM-211: UI: Tab styling should reflect the mockups
csun-metalab/nomi pull request #114
Opened 2018-05-15 22:39 UTC by jazperez

Description: UI: Tab styling should reflect the mockups

Installation: none

Testing: log on, choose any class and observe the tabs on course list

2018-05-16 16:15 UTC, liadGolan requested changes
The tabs should reflect these mockups of the tabs 

https://drive.google.com/open?id=1OU5DjiBQMmhL82OnO-0UWxlXnQ1h2M9l

2018-05-17 00:44 UTC, liadGolan requested changes
When entering a page with tabs, the original choice should be underlined

2018-05-17 23:11 UTC, maseca approved these changes

2018-05-17 23:45 UTC, liadGolan approved these changes
:+1:

2018-05-17 23:45 UTC, merged