NAM-230 -- UI: Back button on "Class Sections" page leads nowhere and needs to be removed
csun-metalab/nomi pull request #136
Opened 2018-05-23 22:17 UTC by maseca

2018-05-23 23:02 UTC, liadGolan requested changes
Back button disappears from pages which need the back button

2018-05-24 19:17 UTC, chippingcolt approved these changes
heyo

2018-05-24 21:07 UTC, chippingcolt approved these changes
kk

2018-05-24 21:11 UTC, liadGolan approved these changes
bueno

2018-05-24 21:11 UTC, merged