NAM-296 -- BUG: When selecting a profile and clicking back before it loads, selecting a new profile loads the canceled profile before the selected one
csun-metalab/nomi pull request #193
Opened 2018-06-25 21:23 UTC by alecnicolas

# Description
To prevent this bug, I disabled the back button from appearing until the student profile is actually loaded as to prevent interrupting the axios call before it finishes.

**EDIT**
The back button is enabled when student profile does not load. The 'x' on the error bar will also take you back to the class page if student profile does not successfully load.
  
# Testing
Open a student profile and verify that the back button does not appear until the student's profile is loaded unless there is an error (such as Mikkal's or Ekene's profile).

2018-06-25 22:40 UTC, liadGolan approved these changes
:hatching_chick:

2018-06-27 16:45 UTC, Tiffufu requested changes
Please disable the back button (and add indicator like greying out) temporarily instead of removing it completely.

2018-07-06 00:22 UTC, Tiffufu requested changes
When I go to Dev III class and click Mikkal and try accessing the profile page, I get an error message and the back button disappears. I should still be able to see the back button if an error occurs.

Also, the error still exists when clicking back before the profile loads and the back button is still nonexistant until the image loads (when it should have been disabled)

2018-07-12 21:35 UTC, Tiffufu approved these changes

2018-07-12 21:41 UTC, merged