NAM-274 -- UI: Refactor and breakup profile vue
csun-metalab/nomi pull request #198
Opened 2018-06-28 21:34 UTC by alecnicolas

# Description
Breaks up `profile.vue` into several smaller components.
  
# Testing
The profile page should still work the same way it did before.

2018-06-28 23:44 UTC, liadGolan requested changes
Add a separate component for the notes

2018-06-29 00:09 UTC, liadGolan approved these changes
:turkey:

2018-06-29 18:56 UTC, Tiffufu approved these changes

2018-06-29 18:56 UTC, merged

2018-07-03 21:54 UTC, frlzjosh reviewed
dude nice