NAM-275 -- UI: Make Bio look nicer
csun-metalab/nomi pull request #210
Opened 2018-07-03 19:09 UTC by alecnicolas

# Description
Was supposed to just make the bio look better but got carried away and made the whole bottom half of the profile more like the mockup. Also you can now press enter when inputting year in term select.
  
# Testing
Make sure the profile page looks appealing to the eye. Type notes, click buttons.

2018-07-03 20:48 UTC, liadGolan approved these changes
:honey_pot:

2018-07-05 23:10 UTC, andrewMETALAB reviewed
please see my comments

2018-07-05 23:59 UTC, andrewMETALAB requested changes
please see my comments

2018-07-10 17:08 UTC, andrewMETALAB approved these changes

2018-07-10 18:52 UTC, merged