NAM-317 -- UI: Redo Cloudy Theme into Dark Theme
csun-metalab/nomi pull request #235
Opened 2018-07-24 01:03 UTC by alecnicolas

# Description
- Implemented Dark theme
- Removed unused classes as found
- Added themes to places where they should've been used but weren't

# Testing
Test the new dark theme in the settings page and make sure nothing is broken or horrendously ugly.

2018-07-24 17:38 UTC, Tiffufu requested changes
We already discussed yesterday, but please make sure that tab/blue color has enough contrast with background color for accessibility.

Other than that, I'm loving the colors you chose and I like the treatment using instead of the usual grey in dark themes. I couldn't have done a better job myself!

2018-07-25 20:13 UTC, BrianLinggadjaja requested changes
The semester selection text on year should be white instead of black.

2018-07-25 22:24 UTC, BrianLinggadjaja approved these changes
Nice color scheme

2018-07-25 22:33 UTC, Tiffufu approved these changes

2018-07-25 22:33 UTC, merged