NAM - 393 -- UI: Going to the settings page from a student profile makes returning to that student profile a long process
csun-metalab/nomi pull request #322
Opened 2018-09-11 22:50 UTC by alecnicolas

# Description
Leaving student profile to go to another view and then returning via students tab should you return you to last viewed class or profile.

# Testing
Go to a student profile then leave the student profile via something in the menu bar and upon returning to the student tab, this should take you back to said student's profile.

2018-09-11 23:57 UTC, BrianLinggadjaja approved these changes
Nice!

2018-09-12 20:43 UTC, chippingcolt requested changes
Yo, so I talked to you already.  Tentatively rejecting just to see if we can replace this logic by stopping rendering using "keep-alive" with the router view.

2018-09-22 00:20 UTC, chippingcolt approved these changes

2018-09-22 00:21 UTC, chippingcolt approved these changes

2018-09-22 00:21 UTC, merged