NAM-90 -- UI: Create list class component
csun-metalab/nomi pull request #38
Opened 2018-02-26 19:38 UTC by maseca

# Description
Create a class list item component which links to relevant course information.  Styling is similar to student list item.
***
# Testing
Verify navigation and styling.  Potential issues may be resolved by running `php artisan cache:clear`

2018-03-09 17:52 UTC, liadGolan requested changes
The Class List and Grid look good, but I am for some reason not able to see the students name in the roster list and matrix. Its an issue only on this branch so I don't know what's causing it.

2018-03-09 17:54 UTC, chippingcolt requested changes
So in gallery card view, no cards/images appear, but you also have scoped styling which is fine, but you also have unused styling file.  Also if you have time we can go over some of the styling.

2018-03-13 16:39 UTC, liadGolan approved these changes

2018-03-15 18:06 UTC, chippingcolt approved these changes

2018-03-15 18:06 UTC, merged