NAM-526 ENG/UI: Change secret from FE to env
csun-metalab/nomi pull request #416
Opened 2019-01-30 17:40 UTC by jazperez

# Description
Add secret to env, and fix how we grab secret on the FE. 
  
# Testing
Add secret_url value to env. 
Log in. Observe  pictures. 

# Installation
None

2019-01-30 19:05 UTC, liadGolan approved these changes
:+1:

2019-02-01 21:25 UTC, matthewfritz requested changes
While I understand the flow of the logic, I would suggest not calling it `SECRET_URL` and `secret-url`. It is a query string parameter. I would suggest having the actual `secret` value be just the actual value that Media requires (as opposed to the `?secret=...` form).

2019-02-01 22:59 UTC, matthewfritz requested changes
The value of `SECRET` is still in the form of `?secret=...`. It should only be the value that Media expects. The various lines of code that consume this value should include `'?secret=' + secret'` and then append the relevant timestamp instead. We don't really want to prescribe URL query parameter key fragments in `.env` values if we know what the consistent pieces are that will be used to build up the URL.

2019-02-01 23:53 UTC, matthewfritz approved these changes

2019-02-01 23:53 UTC, merged