NAM-101 -- ENG & UI: Table sorter
csun-metalab/nomi pull request #44
Opened 2018-03-06 22:07 UTC by maseca

# Description
* This task is complete when students can be sorted based on a particular criteria.
* Sort by last name first.
* Possibly refactor the shuffle, students, and roster.
***
# Testing
* Sorting should default to last name, descending
* Toggling between first and last name sort shouldn't break state horribly

2018-03-09 17:43 UTC, liadGolan requested changes
The sorts that you have are working, but they are not all the sorts we need. Gabe would like to be able to have last name desc/asc and first name desc/asc.

2018-03-13 16:15 UTC, liadGolan approved these changes
:+1:

2018-03-15 18:17 UTC, chippingcolt requested changes
I am getting "undefined undefined" for the names.

2018-03-15 18:26 UTC, chippingcolt approved these changes

2018-03-15 20:27 UTC, merged