NAM-169 -- UI: Vuex Refactor (call Tony to help us)
csun-metalab/nomi pull request #92
Opened 2018-04-25 19:05 UTC by maseca

# Description
> Separate naming convention between grabbed from the backend, and sanitized from the backend/ created on the frontend
Look into deleting redundant blade files
Suggestion for vuex state: in each module include a 'fetched' boolean attribute for the main data that is being requested by the back-end. This will allow for a globally accessible boolean to use when implementing the loading spinner within whichever module needs it.
***
# Testing
* Make sure base functionality works

2018-04-27 16:17 UTC, 404tonynotfound requested changes

2018-05-01 20:23 UTC, jazperez approved these changes
👍🏼Looks good

2018-05-02 02:54 UTC, 404tonynotfound approved these changes

2018-05-02 16:59 UTC, liadGolan approved these changes
:+1:

2018-05-02 16:59 UTC, merged